---
version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: arvanch
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

  gubernator-1:
    image: thrawn01/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # The address that is advertised to other peers
      - GUBER_ADVERTISE_ADDRESS=gubernator-1:81
      # A comma separated list of known gubernator nodes
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
    ports:
      - "8081:81"
      - "8080:80"